alias: Taster WZ Esstisch Aktionen
description: ""
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: "2952514e748246007aa2d6b4719212c8"
      command: "toggle"
  - platform: event
    event_type: zha_event
    event_data:
      device_id: "2952514e748246007aa2d6b4719212c8"
      command: "on"
  - platform: event
    event_type: zha_event
    event_data:
      device_id: "2952514e748246007aa2d6b4719212c8"
      command: "off"

action:
  - choose:
    - conditions:
        - condition: template
          value_template: '{{ trigger.event.data.command == "toggle" }}'
      sequence:
        # HIER DEINE AKTION FÜR EINFACHEN DRUCK EINFÜGEN
        - service: persistent_notification.create
          data:
            title: "Taster"
            message: "Einfacher Druck"
            
    - conditions:
        - condition: template
          value_template: '{{ trigger.event.data.command == "on" }}'
      sequence:
        # HIER DEINE AKTION FÜR DOPPELDRUCK EINFÜGEN
        - service: persistent_notification.create
          data:
            title: "Taster"
            message: "Doppeldruck"
            
    - conditions:
        - condition: template
          value_template: '{{ trigger.event.data.command == "off" }}'
      sequence:
        # HIER DEINE AKTION FÜR LANGEN DRUCK EINFÜGEN
        - service: persistent_notification.create
          data:
            title: "Taster"
            message: "Langer Druck"
            
mode: single
