blueprint:
  name: Sonoff Zigbee Button
  description: Setup actions for three functions of the SONOFF Zigbee button with
    Press, Double Press, and Hold.
  domain: automation
  input:
    zigbee_id:
      name: Device Id
      description: Id of button. Can be found by inspecting zha_event events.
      selector:
        text: {}
    press_action:
      name: Press Action
      description: Action to perform on Press.
      selector:
        action: {}
    double_press_action:
      name: Double Press Action
      description: Action to perform on Double Press.
      selector:
        action: {}
    hold_action:
      name: Hold Action
      description: Action to perform on Hold.
      selector:
        action: {}
  source_url: https://github.com/apollo1220/blueprints/blob/main/sonoff_zigbee_button.yaml
variables:
  zigbee_id: !input 'zigbee_id'
  press_action: !input 'press_action'
  double_press_action: !input 'double_press_action'
  hold_action: !input 'hold_action'
trigger:
- platform: event
  event_type: zha_event
  event_data:
    endpoint_id: 1
    unique_id: !input 'zigbee_id'
action:
- choose:
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "toggle" }}'
    sequence: !input 'press_action'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "on" }}'
    sequence: !input 'double_press_action'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "off" }}'
    sequence: !input 'hold_action'
